name: Postgres MCP CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**/README.md"

jobs:
  postgres-mcp-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Start Docker service
        run: sudo service docker start || true

      - name: Verify Docker is running
        run: docker info

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.9"

      - name: Build Python deps
        run: uv sync

      - name: Run Lint
        run: |
          uv run ruff format --check .
          uv run ruff check .

      - name: Run Type Check
        run: uv run pyright

      # ---------- Docker Build & Push Starts Here ----------

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/postgres-mcp:latest
